#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

if xrandr | grep 'DP-4 connected'
then
	bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9
	bspc monitor DP-4 -d 0
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

sxhkd &
polybar example &
